name: Deploy Blazor WASM PWA to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./dist

      - name: Prepare GitHub Pages content
        run: |
          # Create the pages directory and stff
          mkdir -p ./pages
          
          # Copy wwwroot contents
          cp -r ./dist/wwwroot/* ./pages/
          
          # Copy _content if it exists at the root level
          if [ -d "./dist/_content" ]; then
            mkdir -p ./pages/_content
            cp -r ./dist/_content/* ./pages/_content/
          fi
          
          # Add .nojekyll to prevent Jekyll processing
          touch ./pages/.nojekyll
          
          # Create 404.html for SPA routing
          cp ./pages/index.html ./pages/404.html
          
          # Update base href for GitHub Pages subpath
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' ./pages/index.html
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' ./pages/404.html
          
          # Debug: List structure
          echo "Pages directory structure:"
          find ./pages -name "*.js" | grep -i zxing | head -5
          echo "Looking for _content:"
          find ./pages -path "*/_content/*" -name "*.js" | head -5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4