name: Deploy Blazor WASM PWA to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Publish PWA
        run: dotnet publish Deployment/Deployment.csproj -c Release -o dist

      - name: Fix GitHub Pages Paths
        run: |
          mkdir -p pages
          cp -r dist/wwwroot/* pages/
          
          # Critical: Fix base href
          sed -i 's|<base href="/" />|<base href="/Deployment/" />|g' pages/index.html
          
          # Fix manifest reference
          sed -i 's|href="manifest.json"|href="manifest.webmanifest"|g' pages/index.html
          
          # Rename and fix manifest
          if [ -f "pages/manifest.json" ]; then
            mv pages/manifest.json pages/manifest.webmanifest
            # Fix manifest paths to match GitHub Pages
            sed -i 's|"start_url": "/Deployment/"|"start_url": "/Deployment/"|g' pages/manifest.webmanifest
            sed -i 's|"scope": "/Deployment/"|"scope": "/Deployment/"|g' pages/manifest.webmanifest
          fi
          
          # Use published service worker
          if [ -f "pages/service-worker.published.js" ]; then
            cp pages/service-worker.published.js pages/service-worker.js
          fi
          
          # Create 404.html for SPA routing
          cp pages/index.html pages/404.html
          
          # Disable Jekyll
          touch pages/.nojekyll
          
          # Fix WASM MIME types
          cat > pages/_headers << 'EOF'
          /*.wasm
            Content-Type: application/wasm
          /*.dll
            Content-Type: application/octet-stream
          /*.webmanifest
            Content-Type: application/manifest+json
          /*.js
            Content-Type: application/javascript
          EOF

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4