name: Deploy Blazor WASM PWA to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output publish

      - name: Configure for GitHub Pages
        run: |
          # Debug: Show the complete publish structure
          echo "=== Complete publish directory structure ==="
          find publish -type f | head -20
          
          echo "=== Looking for ZXing files specifically ==="
          find publish -name "*zxing*" -type f
          find publish -path "*ZXingBlazor*" -type f
          
          echo "=== Contents of publish directory ==="
          ls -la publish/
          
          echo "=== Contents of publish/wwwroot ==="
          ls -la publish/wwwroot/ || echo "wwwroot doesn't exist"
          
          # Check if _content exists at different levels
          if [ -d "publish/_content" ]; then
            echo "=== Found _content at publish/_content ==="
            find publish/_content -name "*zxing*" -type f
            # Copy to wwwroot
            mkdir -p publish/wwwroot/_content
            cp -r publish/_content/* publish/wwwroot/_content/
          fi
          
          if [ -d "publish/wwwroot/_content" ]; then
            echo "=== Found _content at publish/wwwroot/_content ==="
            find publish/wwwroot/_content -name "*zxing*" -type f
          fi
          
          # Add .nojekyll to prevent Jekyll processing
          touch publish/wwwroot/.nojekyll
          
          # Create 404.html for SPA routing
          cp publish/wwwroot/index.html publish/wwwroot/404.html
          
          # Update base href for GitHub Pages subpath
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' publish/wwwroot/index.html
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' publish/wwwroot/404.html
          
          echo "=== Final wwwroot structure ==="
          find publish/wwwroot -type f | head -20

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4